

zzc:
  # 用户名
  name: "yecm@qkjr.com.cn"
  # 密码
  password: "xfBJKD6x-vHuQZyrWfZ2"
  # 反欺诈API入口
  cheatListBaseUrl: "https://nezha.intellicredit.cn/api/v2/applications"
  # 黑名单API入口
  backListBaseUrl: "https://nezha.intellicredit.cn/api/v2/blacklist"